
class Meal {
  String name, description, priceAfter, rating, priceBefore, image;
  bool isNew, isPopular,isLiked;
  List<String> images;

  Meal({
    this.image = "",
    this.name = "",
    this.description = "",
    this.priceBefore = "",
    this.priceAfter = "",
    this.rating = "",
    this.isNew = false,
    this.isLiked = false,
    this.isPopular = false,
    List<String> images = const [], // Provide default value as an empty list
  }) : this.images = images;
}

var mealList = [
  Meal(name: "The Full Flock",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/the_full_flock.png",
      images: ["assets/images/item.png","assets/images/item.png","assets/images/item.png","assets/images/item.png"],
      description: "Served with pickles, spring onions and ketchup",
      isLiked: false,
      isNew: true,
      isPopular: false,
      priceAfter: "9"),
  Meal(name: "Crunchy Prawn Roll",
      rating: "4.2",
      priceBefore: "14.99",
      image:"assets/images/meals/crunchy_Prawn_Roll.png",
      images:  ["assets/images/meals/crunchy_Prawn_Roll.png","assets/images/meals/crunchy_Prawn_Roll.png"],
      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: false,
      isPopular: false,
      priceAfter: "11"),
  Meal(name: "Avocado Maki",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/avocado_maki.png",
      images: ["assets/images/meals/avocado_maki.png","assets/images/meals/avocado_maki.png"],
      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: true,
      isPopular: true,
      priceAfter: "9"),
  Meal(name: "Sooshiz Combination",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/sooshiz_combination.png",
      images:["assets/images/meals/sooshiz_combination.png","assets/images/meals/avocado_maki.png"],
      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: false,
      isPopular: true,
      priceAfter: "9"),
];
var likedMealsList = [
  Meal(name: "The Full Flock",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/the_full_flock.png",
      images: ["assets/images/item.png","assets/images/item.png","assets/images/item.png","assets/images/meals/the_full_flock.png","assets/images/meals/the_full_flock.png"],

      description: "Served with pickles, spring onions and ketchup",
      isLiked: true,
      isNew: true,
      isPopular: false,
      priceAfter: "9"),
  Meal(name: "Crunchy Prawn Roll",
      rating: "4.2",
      priceBefore: "14.99",
      image:"assets/images/meals/crunchy_Prawn_Roll.png",
      images:  ["assets/images/meals/crunchy_Prawn_Roll.png","assets/images/meals/crunchy_Prawn_Roll.png"],

      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: true,
      isPopular: false,
      priceAfter: "11"),
  Meal(name: "Avocado Maki",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/avocado_maki.png",
      images: ["assets/images/meals/avocado_maki.png","assets/images/meals/avocado_maki.png"],

      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: true,
      isPopular: true,
      priceAfter: "9"),
  Meal(name: "Avocado Maki",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/avocado_maki.png",
      images: ["assets/images/meals/avocado_maki.png","assets/images/meals/avocado_maki.png"],

      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: true,
      isPopular: false,
      priceAfter: "9"),
  Meal(name: "Sooshiz Combination",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/sooshiz_combination.png",
      images:["assets/images/meals/sooshiz_combination.png","assets/images/meals/avocado_maki.png"],

      description: "Served with pickles, spring onions and ketchup",
      isNew: false,
      isLiked: true,
      isPopular: true,
      priceAfter: "9"),
  Meal(name: "Sooshiz Combination",
      rating: "4.2",
      priceBefore: "12.99",
      image:"assets/images/meals/sooshiz_combination.png",
      images:["assets/images/item.png","assets/images/item.png"],

      description: "Served with pickles, spring onions and ketchup",
      isNew: true,
      isLiked: true,
      isPopular: false,
      priceAfter: "9"),
];